[project]
name = "akshare-one-mcp"
version = "0.1.0"
description = "MCP server for akshare-one"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "akshare-one>=0.1.2",
    "mcp[cli]>=1.6.0",
]
